import Sidebar from "@/components/Sidebar";
import TopNavbar from "@/components/TopNavbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <div className="h-screen flex flex-col">
        {/* Top Navbar */}
        <TopNavbar />

        <div className="flex h-full">
          {/* Sidebar */}
          <Sidebar />

          {/* Content */}
          <div className="bg-contentArea-background flex-1 p-4 text-contentArea-text overflow-y-auto">
            {children}
          </div>
        </div>
      </div>
    </html>
    // <body className={inter.className}>{children}</body>
  );
}
